#!/usr/bin/env perl
use strict;
use warnings;
use Config::Pit;
use WebService::Hatena::Fotolife;

my $config   = pit_get('hatena.ne.jp');
my $filename = '/tmp/gyazolife.png';
unlink $filename if -e $filename;

if (!system("screencapture -i $filename") && -e $filename) {
    my $hatena = WebService::Hatena::Fotolife->new;
       $hatena->username($config->{username});
       $hatena->password($config->{password});

    my ($date)   =  $hatena->createEntry(
        title     => $ARGV[0],
        filename  => $filename,
        folder    => $config->{gyazolife}{folder} || '',
        generator => 'Gyazolife',
    )            =~ /(\d{14})$/;
    my $url      =  sprintf "http://f.hatena.ne.jp/%s/%s", $config->{username}, $date;

    unlink $filename;
    system "echo $url | pbcopy";
    system "open $url";
}
